name: pantheon-docs

proxy:
  gatsby:
    - pantheon-docs.lndo.site:8000

services:
  gatsby:
    type: "node:10"
    port: 8000
    globals:
      gatsby-cli: latest
      firebase-tools: latest
    build:
      - "cd gatsby && npm install"
    command:
      - "cd gatsby && gatsby develop --host 0.0.0.0"

tooling:
  gatsby:
    service: gatsby
    cmd: "cd /app/gatsby && gatsby"
  firebase:
    service: gatsby
  npm:
    service: gatsby
    cmd: "cd /app/gatsby && npm"